all: prob01bin prob02bin prob03bin
	
prob01bin: prob01.c
	gcc -o prob01 prob01.c

prob02bin: prob02.c
	gcc -o prob02 prob02.c

prob03bin: prob03.c
	gcc -o prob03 prob03.c

clean:
	rm -rf *.o
	rm -rf prob01
	rm -rf prob02
	rm -rf prob03
